-- Replace DATASET_NAME

CREATE OR REPLACE PROCEDURE
`DATASET_NAME.PROC_CLI_UNION_TABLE`(NAME_REGEX STRING,IS_NEW_TABLE BOOL,FILE_NAME STRING,ENV STRING )
BEGIN
DECLARE MERGED_DATE STRING;
DECLARE TABLE_NAME STRING;
DECLARE EXECUTION_QUERY STRING;
DECLARE CREATION_QUERY STRING;

SET FILE_NAME = IFNULL(FILE_NAME, "client_merged");
SET ENV = IFNULL(ENV, "DEV");
SET TABLE_NAME = CONCAT(FILE_NAME, IF(ENV = "PROD", "", CONCAT("_", ENV)));

SET CREATION_QUERY = 
IF(IS_NEW_TABLE,
"CREATE OR REPLACE TABLE `DATASET_NAME.TABLE_NAME` ( name STRING,sex STRING,mail STRING,client_movie_genres STRING ,client_language_spoken STRING,client_car STRING,credit_score INT ,timestamp TIMESTAMP)", "" ) ;

SET CREATION_QUERY = REGEXP_REPLACE(CREATION_QUERY, "TABLE_NAME", TABLE_NAME);
EXECUTE IMMEDIATE CREATION_QUERY;


SET EXECUTION_QUERY =
"INSERT INTO `DATASET_NAME.TABLE_NAME` ( name ,sex ,mail ,client_movie_genres ,client_language_spoken,client_car,credit_score) SELECT DISTINCT name,sex,mail,client_movie_genres,client_language_spoken,client_car,credit_score FROM `DATASET_NAME.NAME_REGEX*` ORDER BY credit_score DESC";


SET EXECUTION_QUERY = REGEXP_REPLACE(EXECUTION_QUERY, "NAME_REGEX", NAME_REGEX);
SET EXECUTION_QUERY = REGEXP_REPLACE(EXECUTION_QUERY, "TABLE_NAME", TABLE_NAME);
EXECUTE IMMEDIATE EXECUTION_QUERY;
END;



CALL `DATASET_NAME.PROC_CLI_UNION_TABLE` ("client", TRUE,"union_client_merged", "PROD");